/* V3 views use the existing database, forms, navigation and save flow. */
'use strict';
let dailyState;
const icons={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8m-4 0h4v4"/>',leaf:'<path d="M20 3C8 2 2 7 5 15s15 4 15-12Z M4 21 15 10"/>',folder:'<path d="M3 7V5h6l2 2h10v13H3Z"/>',arrow:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',note:'<path d="M5 3h14v18H5ZM8 8h8M8 12h8M8 16h5"/>',chart:'<path d="M5 20V13h3v7m3 0V8h3v12m3 0V3h3v17"/>',gym:'<path d="M7 12h10M3 8v8m4-10v12m10-12v12m4-10v8"/>',moon:'<path d="M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10Z"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
const textName=s=>`<bdi dir="auto">${esc(s)}</bdi>`;
const action=(name,id='')=>`data-action="${name}" data-id="${esc(id)}"`;
const section=(title,arabic,body,button='')=>`<section class="v3-section"><div class="v3-heading"><h2>${title}<small lang="ar" dir="rtl">${arabic}</small></h2>${button}</div>${body}</section>`;
const link=(label,view)=>`<button class="textbtn" ${action('navigate',view)}>${label} ${icon('arrow')}</button>`;
const meter=(value)=>value===null?'':`<div class="v3-meter" role="progressbar" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="100"><i style="width:${value}%"></i></div>`;
function projectTile(p){return `<button class="project-tile" ${action('project',p.id)}><span class="tile-icon">${icon('folder')}</span><span class="grow"><strong dir="auto">${textName(p.name)}</strong><small>${esc(p.status)} · ${p.progress===null?'Progress not set':`${p.progress}% · ${p.progressSource}`}</small>${meter(p.progress)}</span>${icon('arrow')}</button>`}
function habitSummary(j){const h=j.habit;return `<article class="habit-summary"><span class="tile-icon habit-icon">${icon(/gym|جيم/i.test(h.name)?'gym':'leaf')}</span><button class="habit-summary-main" dir="auto" ${action('journey',h.id)}><strong dir="auto">${textName(h.name)}</strong><span class="small habit-stat-line">${j.streak} ${j.unit} streak${j.rate===null?'':` · ${j.rate}% ${j.weekly?'weekly adherence':'consistency'} · 30d`}</span><span class="recent-dots" aria-label="Recent seven days">${j.recent.map(d=>`<i class="${d.state} ${d.today?'is-today':''}" title="${d.date}: ${d.state}"></i>`).join('')}</span><span class="small cycle-caption">${j.anchor?'Day '+j.position+' / 30':'Ready to start'}${j.weekly&&j.periodDone?' · Week met':''}</span></button><button class="check ${j.todayDone?'done':''}" ${action('track',h.id)} aria-label="${j.todayDone?'Update':'Track'} ${esc(h.name)}">${j.todayDone?icon('check'):icon('plus')}</button></article>`}
function journeyCard(j,detail=false){const h=j.habit;const periodCounts=j.weekly?`${j.completed} / ${j.known} evaluable weeks`:`${j.completed} / ${j.known} evaluable days`;return `<article class="journey-card card" data-habit="${esc(h.id)}"><div class="row"><span class="tile-icon">${icon(/gym|جيم/i.test(h.name)?'gym':'leaf')}</span><div class="grow"><h2 dir="auto">${textName(h.name)}</h2><span class="small">${esc(h.frequency)} · ${h.tracking==='quantity'?`${h.target} ${esc(h.unit||'units')}`:'Yes / No'}</span></div><button class="textbtn" ${action('edit-habit',h.id)}>Edit</button></div><div class="journey-metrics"><div><b>${j.streak}</b><small>${j.unit} streak</small></div><div><b>${j.rate===null?'—':j.rate+'%'}</b><small>${j.weekly?'Weekly adherence':'Recorded consistency'}</small></div><div><b>${j.anchor?j.position:'—'}<small> / 30</small></b><small>Cycle day</small></div></div><p class="small">${periodCounts} completed in the last 30 days.${j.unknown?' Unrecorded periods excluded.':''}</p><div class="journey-grid" role="list" aria-label="30-day habit journey">${j.cells.map(d=>`<div role="listitem" class="journey-day ${d.state} ${d.today?'is-today':''}" aria-label="Day ${d.number}, ${d.date}: ${d.state}${d.today?', today':''}"><span>${d.state==='completed'?'✓':d.state==='missed'?'—':d.number}</span><small>${new Date(d.date+'T12:00:00').getDate()}</small></div>`).join('')}</div>${j.weekly?`<div class="week-adherence">${j.cycleWeeks.map(w=>`<span class="${w.state}">Week of <bdi>${w.date.slice(5)}</bdi> · ${w.state==='completed'?'met':w.state==='missed'?'not met':w.state}</span>`).join('')}</div><p class="small">One completed daily entry meets the weekly requirement. Unlogged days are not daily failures.</p>`:''}<div class="journey-legend"><span>✓ Completed</span><span>○ Unrecorded</span><span>— Missed</span><span>◌ Future</span><span class="today-label">Today outlined</span></div><p class="small">${j.anchor?`${j.anchorLabel}: <bdi>${j.anchor}</bdi>`:j.anchorLabel}. ${j.anchor?'Cycle '+j.cycle+' · ':''}<bdi>${j.start}</bdi> – <bdi>${j.end}</bdi></p>${detail?'<p class="small">Consistency excludes future and unknown periods. Past quantities use the current target; earlier target settings were not saved.</p>':''}<button class="primary full" ${action('track',h.id)}>${icon(j.todayDone?'check':'plus')} ${h.tracking==='quantity'?'Log today’s amount':j.todayDone?'Completed today · tap to undo':'Mark today complete'}</button></article>`}
function renderV3(s){dailyState=s;document.body.dataset.mode=s.mode.toLowerCase();document.body.dataset.time=s.hour>=18?'evening':s.hour<12?'morning':'day';
 const focus=s.focus,focusBody=focus?`<button class="focus-body" ${action('project',focus.id)}><strong dir="auto">${textName(focus.name)}</strong><p>${textName(focus.milestone||'Choose one useful next step for this project.')}</p>${focus.progress!==null?`${meter(focus.progress)}<small>${focus.progress}% · ${focus.progressSource}</small>`:''}<span class="focus-arrow">${icon('arrow')}</span></button>`:`<button class="focus-body" onclick="checkin('morning')"><strong dir="auto">${textName(s.checkin?.priority||'Choose what matters today.')}</strong><p>Set a direction in your morning check-in.</p></button>`;
 const tasks=s.topTasks.length?s.topTasks.map(t=>`<div class="v3-task"><button class="check" ${action('task-done',t.id)} aria-label="Complete ${esc(t.name)}"></button><button class="task-name" ${action('edit-task',t.id)}>${textName(t.name)}${t.date<s.today?'<small>Overdue · '+esc(t.date)+'</small>':''}</button><span class="priority ${String(t.priority).toLowerCase()}">${esc(t.priority||'Medium')}</span></div>`).join(''):`<div class="empty">${s.todayTasks.length?'Today’s tasks are complete.':'A little space to plan your day.'}<button class="textbtn" onclick="task()">＋ Add a task</button></div>`;
 const habitBody=s.habits.length?(s.mode==='Execution'?[...s.habits].sort((a,b)=>Number(a.periodDone)-Number(b.periodDone)):s.habits).slice(0,3).map(habitSummary).join(''):'<div class="empty">Build consistency with one small habit.<button class="textbtn" onclick="habit()">＋ Add a habit</button></div>';
 const done=s.todayTasks.filter(t=>t.done).length,hDone=s.habits.filter(h=>h.periodDone).length;
 const stats=`<div class="v3-stats"><div><b>${done}<small> / ${s.todayTasks.length}</small></b><span>Today’s tasks</span>${meter(BetterLifeDaily.percentage(done,s.todayTasks.length))}</div><div><b>${hDone}<small> / ${s.habits.length}</small></b><span>Habit periods met</span>${meter(BetterLifeDaily.percentage(hDone,s.habits.length))}</div></div>`;
 const reminder=s.overdue.length?`${s.overdue.length} unfinished ${s.overdue.length===1?'task needs':'tasks need'} a new moment. Choose one to move forward.`:s.mode==='Review'?'Keep one useful lesson from today. Your weekly review is ready when you are.':s.checkin?.priority||s.message;
 const noteAction=s.overdue.length?'tasks':s.mode==='Review'?'reviews':'checkins';
 $('home').innerHTML=`${storageError?'<div class="notice" role="alert">Saved data could not be read. Saving is disabled to protect it. Your stored data has not been replaced.</div>':''}<div class="v3-hero" style="--hero-image:url('${s.image}')"><div class="hero-top"><span class="eyebrow">YOUR DAY, WITH INTENTION</span><button class="hero-checkin" onclick="checkin('${s.hour>=18?'night':'morning'}')" aria-label="Open check-in">${icon(s.hour>=18?'moon':'sun')}</button></div><p class="hero-date">${new Date(s.today+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1>${s.greeting}${db.settings?.name?',<br>'+textName(db.settings.name):'.'}</h1><span class="mode-pill">${icon(s.mode==='Calm'?'leaf':s.mode==='Review'?'moon':'focus')}${s.mode} mode</span><p class="hero-message">${esc(s.message)}</p></div><article class="v3-focus"><div class="row"><span class="focus-label">${icon('focus')} TODAY’S FOCUS</span>${focus?`<span class="primary-tag">${esc(focus.status)}</span>`:''}</div>${focusBody}</article>${section('Today’s tasks','مهام اليوم',`<div class="v3-card">${tasks}</div>`,link('See all','tasks'))}${section('Your habits','عاداتك',`<div class="v3-card">${habitBody}</div>`,link('Journey','habits'))}${section('Active projects','المشاريع',`<div class="v3-card project-stack">${s.projects.length?s.projects.slice(0,4).map(projectTile).join(''):'<div class="empty">No active projects.</div>'}</div>`,link('See all','projects'))}${section('Today at a glance','لمحة اليوم',stats)}<button class="insight-card" ${action('context',noteAction)}><span class="tile-icon">${icon('leaf')}</span><span><small>${s.mode==='Reset'?'A FRESH STEP':'A MOMENT FOR YOU'}</small><strong dir="auto">${textName(reminder)}</strong></span>${icon('arrow')}</button>${section('This week','هذا الأسبوع',`<div class="week-strip">${s.week.map(d=>`<div class="${d.today?'current':''} ${d.future?'future':''}"><small>${new Date(d.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</small><b>${Number(d.date.slice(-2))}</b><i class="${d.activity?'active':''}"></i></div>`).join('')}</div><p class="small week-caption">Dots show recorded task or habit completions.</p>`)}${section('Make a little progress','خطوة صغيرة',`<div class="quick-grid"><button onclick="task()">${icon('plus')}<span>Add task</span></button><button onclick="habit()">${icon('leaf')}<span>Add habit</span></button><button onclick="goal()">${icon('focus')}<span>Add goal</span></button><button onclick="journal()">${icon('note')}<span>Quick note</span></button></div>`)}<p class="home-footer">Small steps. A life that feels like yours.</p>`;
 $('habitJourneyIntro').innerHTML=`<div class="journey-intro"><span class="mode-pill">${icon('leaf')}${s.mode} mode</span><h2>Your 30-day journey</h2><p>${esc(s.message)}</p><p class="mode-guidance">${({Focus:'Keep attention on today’s next habit.',Execution:'Log one habit, then take the next step.',Calm:'No rush. Choose a practice that supports you.',Reset:'Continue this journey with one small action today.',Review:'Look at the pattern, including the days you did show up.',Achievement:'Your completed days are building a visible journey.'})[s.mode]}</p><p lang="ar" dir="rtl">خطوة صغيرة كل يوم</p></div>`;
 $('hl').innerHTML=s.habits.length?s.habits.map(j=>journeyCard(j)).join(''):'<div class="card empty">Your journey starts with your first habit.<button class="primary full" onclick="habit()">＋ Add a habit</button></div>';
 $('projectList').innerHTML=(db.projects||[]).map(p=>projectTile(BetterLifeDaily.projectState(db,p))).join('')||'<div class="empty">No projects yet.</div>';
}
function openJourney(id){const h=db.habits.find(h=>h.id===id);if(!h)return;open(`<div class="row"><h2>Habit journey</h2><button class="secondary" onclick="closeModal()">Close</button></div>${journeyCard({...BetterLifeDaily.journey(db,h),habit:h},true)}`);$('sheet').dataset.journey=id}
function projectDetail(id){const p=db.projects.find(p=>p.id===id);if(!p)return;const s=BetterLifeDaily.projectState(db,p);open(`<div class="row"><span class="mode-pill">${esc(p.status)}</span><button class="secondary" onclick="closeModal()">Close</button></div><h2 dir="auto">${textName(p.name)}</h2><p>${textName(p.milestone||'No milestone set yet.')}</p>${meter(s.progress)}<p class="small">${s.progress===null?'Progress not set':s.progress+'% · '+s.progressSource}</p><h3>Linked tasks</h3>${s.tasks.length?s.tasks.map(t=>`<div class="item">${icon(t.done?'check':'note')}<span>${textName(t.name)}</span></div>`).join(''):'<p class="small">Link existing tasks to calculate progress.</p>'}<h3>Linked goals</h3>${s.goals.map(g=>`<p>${textName(g.name)} · ${Number(g.progress)||0}% manual goal progress</p>`).join('')||'<p class="small">No goals linked.</p>'}<button class="primary full" ${action('edit-project',id)}>Edit project & links</button>`)}
function projectForm(id=''){const p=db.projects.find(p=>p.id===id)||{};open(`<h2>${id?'Edit':'Add'} Project</h2><label>Name</label><input id="projectName" dir="auto" value="${esc(p.name)}"><label>Status</label><select id="projectStatus">${['Primary','Active','Paused','Completed'].map(s=>`<option ${s===(p.status||'Active')?'selected':''}>${s}</option>`).join('')}</select><label>Current milestone</label><input id="projectMilestone" dir="auto" value="${esc(p.milestone)}"><label>Manual progress (optional)</label><input id="projectProgress" type="number" min="0" max="100" value="${esc(p.manualProgress??'')}" placeholder="Leave empty to use linked tasks"><p class="small">An explicit manual value takes precedence. Otherwise linked task completion supplies progress; no linked tasks means no percentage.</p><fieldset><legend>Linked tasks</legend>${db.tasks.map(t=>`<label class="choice"><input type="checkbox" name="projectTask" value="${esc(t.id)}" ${(p.taskIds||[]).includes(t.id)?'checked':''}>${textName(t.name)}</label>`).join('')||'<p class="small">Add tasks first to link them.</p>'}</fieldset><fieldset><legend>Linked goals</legend>${db.goals.map(g=>`<label class="choice"><input type="checkbox" name="projectGoal" value="${esc(g.id)}" ${(p.goalIds||[]).includes(g.id)?'checked':''}>${textName(g.name)}</label>`).join('')||'<p class="small">No goals yet.</p>'}</fieldset><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" ${action('save-project',id)}>Save project</button></div>`)}
function saveProject(id){const name=$('projectName').value.trim();if(!name)return;const input=$('projectProgress'),value=input.value.trim();if(value!==''&&(!input.checkValidity()||!Number.isFinite(Number(value)))){input.reportValidity();return}const o={name,status:$('projectStatus').value,milestone:$('projectMilestone').value.trim(),manualProgress:value===''?null:Number(value),taskIds:[...document.querySelectorAll('[name=projectTask]:checked')].map(n=>n.value),goalIds:[...document.querySelectorAll('[name=projectGoal]:checked')].map(n=>n.value)};if(o.status==='Primary')db.projects.forEach(p=>{if(p.id!==id&&p.status==='Primary')p.status='Active'});const p=db.projects.find(p=>p.id===id);p?Object.assign(p,o):db.projects.push({id:window.crypto?.randomUUID?.()||Date.now().toString(36),...o});if(save())closeModal()}
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b)return;const id=b.dataset.id;switch(b.dataset.action){case'navigate':show(id);break;case'context':if(id==='tasks')show(id);else{mtab=id;show('more')}break;case'project':projectDetail(id);break;case'edit-project':projectForm(id);break;case'save-project':saveProject(id);break;case'journey':openJourney(id);break;case'edit-habit':habit(db.habits.find(h=>h.id===id));break;case'track':{const h=db.habits.find(h=>h.id===id);const modalJourney=$('modal').classList.contains('open')&&$('sheet').dataset.journey===id;toggleHabit(id);if(modalJourney&&h?.tracking!=='quantity')openJourney(id);break}case'task-done':taskDone(id);break;case'edit-task':task(db.tasks.find(t=>t.id===id));break}});
// Refresh on return/midnight without disrupting an open form or stealing focus.
let clockSignature='';function refreshClock(){const n=new Date(),signature=BetterLifeDaily.dateKey(n)+':'+n.getHours();if(signature!==clockSignature&&!$('modal').classList.contains('open')){clockSignature=signature;render()}}
setInterval(refreshClock,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshClock()});
