/* Run against a local preview with Playwright; only disposable browser storage is used. */
const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const baseURL=process.env.BETTER_LIFE_URL||'http://127.0.0.1:8765/';
const output=process.env.BETTER_LIFE_QA_DIR||'/private/tmp/better-life-qa';fs.mkdirSync(output,{recursive:true});
(async()=>{
for(const [engine,browserType] of [['chromium',chromium],['webkit',webkit]]){
const browser=await browserType.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,timezoneId:'Africa/Cairo'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(baseURL);await page.waitForSelector('.v3-hero');
assert.deepEqual(await page.locator('nav button').evaluateAll(ns=>ns.map(n=>n.dataset.view)),['home','tasks','habits','goals','more']);
assert.equal(await page.locator('.project-tile').first().getAttribute('data-id'),'project-sports-center');assert.ok((await page.locator('#home').innerText()).includes('Progress not set'));
const fixture=await page.evaluate(()=>{const today=day(),logs={};for(let i=1;i<=65;i++)logs['prayer-'+BetterLifeDaily.add(today,-i)]=true;for(let i=1;i<=6;i++)logs['gym-'+BetterLifeDaily.add(BetterLifeDaily.monday(today),-7*i)]=true;return {schemaVersion:3,habits:[{id:'prayer',name:'الصلاة',tracking:'yesno',frequency:'Daily',target:1},{id:'gym',name:'Gym / الجيم',tracking:'quantity',frequency:'Weekly',target:30,unit:'minutes'},{id:'calm',name:'الهدوء النفسي والرضا',tracking:'yesno',frequency:'Daily',target:1}],logs,tasks:[{id:'t1',name:'QA task — مراجعة الخطة',date:today,priority:'High',done:false,recurring:'daily'},{id:'t2',name:'QA completed task',date:today,priority:'Medium',done:true},{id:'t3',name:'QA overdue task',date:BetterLifeDaily.add(today,-1),done:false}],journal:[{id:'j1',date:today+'T12:00:00',text:'ملاحظة اختبار — private fixture',entryType:'Daily'}],goals:[{id:'g1',name:'QA goal',status:'Active',progress:12}],income:[{id:'inc1',source:'QA source',amount:100,date:today}],expenses:[{id:'ex1',category:'Other',amount:20,date:today}],lifeAreas:[{id:'a1',name:'Health',custom:'keep'}],financeCategories:[],reviews:[{id:'r1',type:'Weekly',date:today,worked:'QA worked',adjust:'QA adjust'}],experiences:[{id:'e1',name:'QA trip',status:'Planned'}],customData:{preserve:true}}});
await page.evaluate(data=>localStorage.setItem('better-life-v2',JSON.stringify(data)),fixture);await page.reload();await page.waitForSelector('.v3-hero');
assert.deepEqual(await page.evaluate(()=>db.logs),fixture.logs);assert.equal(await page.evaluate(()=>BetterLifeDaily.journey(db,db.habits[0]).streak),65);
await page.screenshot({path:output+'/'+engine+'-home.png',fullPage:true});
await page.locator('[data-view=habits]').click();assert.equal(await page.locator('#hl .journey-day').count(),90);await page.screenshot({path:output+'/'+engine+'-habits.png',fullPage:true});
await page.locator('#hl [data-action=track][data-id=prayer]').click();assert.equal(await page.evaluate(()=>BetterLifeDaily.journey(db,db.habits[0]).streak),66);
await page.locator('#hl [data-action=track][data-id=gym]').click();await page.locator('#hval').fill('30');await page.locator('#sheet button',{}).filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>BetterLifeDaily.journey(db,db.habits[1]).periodDone),true);
// New habits get an explicit start, existing ones do not.
await page.locator('#habits button').filter({hasText:'＋ Add'}).click();await page.locator('#hn').fill('QA new habit');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.habits.at(-1).journeyStartDate===day()),true);assert.equal(await page.evaluate(()=>db.habits[0].journeyStartDate),undefined);
await page.locator('[data-view=home]').click();await page.locator('#home [data-action=journey]').first().click();assert.equal(await page.locator('#sheet .journey-day').count(),30);await page.keyboard.press('Escape');assert.equal(await page.locator('#modal').getAttribute('class'),'modal');
// Real task form, completion, and recurrence.
await page.locator('[data-view=tasks]').click();await page.locator('#tasks button').filter({hasText:'＋ Add'}).click();await page.locator('#tn').fill('QA created task');await page.locator('#sheet button').filter({hasText:'Save Task'}).click();assert.equal(await page.evaluate(()=>db.tasks.some(t=>t.name==='QA created task')),true);
await page.locator('#taskList .item').filter({hasText:'QA task —'}).locator('.check').click();assert.equal(await page.evaluate(()=>db.tasks.filter(t=>t.previous==='t1').length),1);
// Project links/manual progress and primary designation.
await page.locator('[data-view=more]').click();await page.getByRole('button',{name:'Projects',exact:false}).filter({hasText:'Projects'}).first().click();await page.locator('#projectList [data-id=project-sports-center]').click();await page.locator('[data-action=edit-project]').click();await page.locator('[name=projectTask][value=t1]').check();await page.locator('[name=projectTask][value=t3]').check();await page.locator('#projectMilestone').fill('QA milestone');await page.locator('[data-action=save-project]').click();assert.equal(await page.evaluate(()=>BetterLifeDaily.projectState(db,db.projects[0]).progress),50);
await page.locator('#projectList [data-id=project-sports-center]').click();await page.locator('[data-action=edit-project]').click();await page.locator('#projectProgress').fill('25');await page.locator('[data-action=save-project]').click();assert.equal(await page.evaluate(()=>BetterLifeDaily.projectState(db,db.projects[0]).progress),25);
// Goals and journal use their existing forms.
await page.locator('[data-view=goals]').click();await page.locator('#goals button').filter({hasText:'＋ New'}).click();await page.locator('#gn').fill('QA new goal');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.goals.at(-1).name),'QA new goal');
await page.locator('[data-view=more]').click();await page.locator('#mc button').filter({hasText:'Journal'}).click();await page.locator('#journal button').filter({hasText:'＋ New'}).click();await page.locator('#jtx').fill('QA journal entry');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.journal[0].text),'QA journal entry');
// Every More tool renders with populated data; exercise finance, area and review saves.
for(const key of ['checkins','finance','life','reviews','insights','experiences','settings']){await page.evaluate(k=>{mtab=k;show('more')},key);assert.ok((await page.locator('#mc').innerText()).length>10)}
await page.evaluate(()=>{mtab='finance';show('more');incomeForm()});await page.locator('#is').fill('QA extra income');await page.locator('#ia').fill('42');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.income.at(-1).amount),42);
await page.evaluate(()=>{mtab='life';show('more');areaForm()});await page.locator('#an').fill('QA life area');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.lifeAreas.at(-1).name),'QA life area');
await page.evaluate(()=>{mtab='reviews';show('more');review('Weekly')});await page.locator('#rc').fill('QA next adjustment');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.reviews.at(-1).adjust),'QA next adjustment');
await page.evaluate(()=>{mtab='experiences';show('more');experienceForm()});await page.locator('#exname').fill('QA new experience');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>db.experiences.at(-1).name),'QA new experience');
await page.evaluate(()=>{mtab='checkins';show('more');checkin('morning')});await page.locator('#int').selectOption('Calm');await page.locator('#sheet button').filter({hasText:/^Save$/}).click();assert.equal(await page.evaluate(()=>dailyState.mode),'Calm');
// All old logs remain identical, except the explicitly changed today entries.
const after=await page.evaluate(()=>db.logs);for(const [key,value] of Object.entries(fixture.logs))assert.equal(after[key],value);assert.deepEqual(await page.evaluate(()=>db.customData),fixture.customData);
await page.reload();assert.equal(await page.evaluate(()=>db.projects[0].manualProgress),25);assert.equal(await page.evaluate(()=>db.habits[0].id),'prayer');
// Overflow checks inspect actual boxes, not just overflow:hidden on the body.
for(const width of [320,375,390,430,768]){await page.setViewportSize({width,height:844});for(const view of ['home','tasks','habits','goals','projects','more','journal']){await page.evaluate(v=>show(v),view);const overflow=await page.evaluate(()=>[...document.querySelectorAll('.view.active *')].filter(e=>{const r=e.getBoundingClientRect();const clipped=e.closest('.tabs');return !clipped&&r.width&&getComputedStyle(e).position!=='fixed'&&(r.right>innerWidth+1||r.left< -1)}).map(e=>e.className).slice(0,8));assert.deepEqual(overflow,[],`${engine} ${width} ${view}`)}}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>show('home'));
await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
const cached=await page.evaluate(async()=>{const c=await caches.open('better-life-v10');return (await c.keys()).map(r=>new URL(r.url).pathname)});for(const f of ['index.html','daily-state.js','v3-ui.js','v3.css','assets/daily-landscape.webp','assets/calm-sky.webp'])assert.ok(cached.some(p=>p.endsWith(f)),`cached ${f}`);
const manifest=await page.evaluate(async()=>await (await fetch('manifest.json')).json());assert.equal(manifest.display,'standalone');assert.equal(manifest.icons.some(i=>i.sizes==='192x192'),true);assert.equal(manifest.icons.some(i=>i.sizes==='512x512'),true);
if(engine==='chromium'){await context.setOffline(true);await page.reload();await page.waitForSelector('.v3-hero');await page.locator('[data-view=habits]').click();assert.equal(await page.locator('#hl .journey-day').count(),120);await context.setOffline(false)} // WebKit network-loss reload is covered by pwa-upgrade.cjs.
assert.deepEqual(errors,[],`${engine}: no uncaught JS errors`);
// Image failure must leave a readable, functional hero.
const fallback=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await fallback.route('**/*.webp',route=>route.abort());const fp=await fallback.newPage();await fp.goto(baseURL);assert.ok(await fp.locator('.v3-hero').isVisible());assert.equal(await fp.locator('.v3-hero').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(32, 69, 94)');await fp.screenshot({path:output+'/'+engine+'-fallback.png',fullPage:true});await fallback.close();
// Malformed storage must not be overwritten on save.
const bad=await browser.newContext();const bp=await bad.newPage();await bp.goto(baseURL);await bp.evaluate(()=>localStorage.setItem('better-life-v2','{broken'));await bp.reload();assert.ok(await bp.locator('[role=alert]').isVisible());bp.on('dialog',d=>d.accept());await bp.evaluate(()=>save());assert.equal(await bp.evaluate(()=>localStorage.getItem('better-life-v2')),'{broken');await bad.close();
console.log(engine+': PASS — migration preservation, CRUD flows, projects, modal, 5 widths, assets, manifest, fallback, malformed storage, no JS errors');await browser.close();
}
})().catch(e=>{console.error(e);process.exit(1)});
