const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const D=require('../daily-state.js');
const h={id:'habit-with-dash',name:'الصلاة',frequency:'Daily',tracking:'yesno',target:1};
const today='2026-09-29';
const database=(logs={},habit=h)=>({habits:[habit],logs,tasks:[],goals:[],checkins:[],projects:[]});
test('unknown history is not failure and future logs never count',()=>{const db=database({[h.id+'-2026-09-20']:true,[h.id+'-2026-10-01']:true});const j=D.journey(db,h,today);assert.equal(j.anchor,'2026-09-20');assert.equal(j.anchorLabel,'Earliest recorded history');assert.equal(j.cells[1].state,'unknown');assert.equal(j.cells[11].state,'future');assert.equal(j.known,1);assert.equal(j.rate,100);assert.equal(j.cycleCompleted,1);assert.equal(h.journeyStartDate,undefined)});
test('no history has no percentage and no invented start',()=>{const j=D.journey(database(),h,today);assert.equal(j.anchor,null);assert.equal(j.position,0);assert.equal(j.rate,null);assert.equal(j.streak,0);assert.equal(j.cells[0].state,'pending');assert.equal(j.cells[1].state,'future')});
test('65 day streak survives an incomplete current day',()=>{const logs={};for(let i=1;i<=65;i++)logs[h.id+'-'+D.add(today,-i)]=true;const db=database(logs);assert.equal(D.journey(db,h,today).streak,65);logs[h.id+'-'+today]=true;assert.equal(D.journey(db,h,today).streak,66)});
test('explicit start allows elapsed misses but future never fails',()=>{const habit={...h,journeyStartDate:'2026-09-27'};const j=D.journey(database({},habit),habit,today);assert.deepEqual(j.cells.slice(0,4).map(x=>x.state),['missed','missed','pending','future']);assert.equal(j.rate,0)});
test('cycle rolls over on day 31 without removing logs',()=>{const habit={...h,journeyStartDate:'2026-08-30'},db=database({[h.id+'-2026-08-30']:true},habit),before=JSON.stringify(db);const j=D.journey(db,habit,today);assert.equal(j.cycle,2);assert.equal(j.start,today);assert.equal(j.position,1);assert.equal(JSON.stringify(db),before)});
test('quantity uses target including fractional target',()=>{const habit={...h,tracking:'quantity',target:.5};const db=database({[h.id+'-'+today]:.4},habit);assert.equal(D.journey(db,habit,today).todayDone,false);db.logs[h.id+'-'+today]=.5;assert.equal(D.journey(db,habit,today).todayDone,true)});
test('weekly completion meets week once and preserves previous weekly streak',()=>{const habit={...h,frequency:'Weekly'},logs={};for(let i=1;i<=8;i++)logs[h.id+'-'+D.add(D.monday(today),-i*7)]=true;let j=D.journey(database(logs,habit),habit,today);assert.equal(j.streak,8);assert.equal(j.weekly,true);assert.equal(j.rate,100);logs[h.id+'-'+today]=true;j=D.journey(database(logs,habit),habit,today);assert.equal(j.streak,9);assert.equal(j.periodDone,true);assert.equal(j.periods.at(-1).state,'completed')});
test('missing legacy weeks stay unknown; explicit complete past weeks can miss',()=>{const weekly={...h,frequency:'Weekly'};assert.equal(D.history(database({},weekly),weekly,today).weekState('2026-09-21'),'unknown');const started={...weekly,journeyStartDate:'2026-09-21'};assert.equal(D.history(database({},started),started,today).weekState('2026-09-21'),'missed');assert.equal(D.history(database({},started),started,today).weekState('2026-09-28'),'pending')});
test('local date arithmetic crosses leap day and year',()=>{assert.equal(D.add('2024-02-28',1),'2024-02-29');assert.equal(D.add('2026-12-31',1),'2027-01-01');assert.equal(D.diff('2026-03-30','2026-03-28'),2);assert.equal(D.valid('2026-02-30'),false)});
test('project seeding is idempotent and never produces fake progress',()=>{const seed=database();delete seed.projects;const db=D.migrateV3(seed);assert.equal(db.projects.length,4);assert.equal(db.projects.some(p=>p.name==='Better Life'),false);assert.deepEqual(D.migrateV3(db),db);assert.equal(D.projectState(db,db.projects[0]).progress,null);const p={...db.projects[0],taskIds:['a','b']};db.tasks=[{id:'a',done:true},{id:'b',done:false}];assert.equal(D.projectState(db,p).progress,50);assert.equal(D.projectState(db,{...p,manualProgress:0}).progress,0);assert.equal(D.projectState(db,{...p,taskIds:['deleted']}).progress,null)});
test('all modes follow real inputs and empty data never becomes reset/achievement',()=>{const now=new Date(today+'T10:00:00');const db=database();db.habits=[];assert.equal(D.buildDailyState(db,now).mode,'Focus');db.tasks=[{id:'t',date:today,priority:'Medium',done:false}];assert.equal(D.buildDailyState(db,now).mode,'Execution');db.tasks[0].priority='High';assert.equal(D.buildDailyState(db,now).mode,'Focus');db.tasks[0].done=true;assert.equal(D.buildDailyState(db,now).mode,'Achievement');db.checkins=[{date:today,intention:'Recovery'}];assert.equal(D.buildDailyState(db,now).mode,'Calm');db.checkins=[];db.tasks=[];assert.equal(D.buildDailyState(db,new Date(today+'T20:00:00')).mode,'Review');db.habits=[{...h,journeyStartDate:'2026-09-20'}];assert.equal(D.buildDailyState(db,now).mode,'Reset')});
// Exercise the real application's migration, not a parallel test implementation.
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');const core=html.slice(html.indexOf("const K="),html.indexOf('let storageError='));
const ctx={BetterLifeDaily:D};vm.createContext(ctx);vm.runInContext(core+';this.runMigration=migrate;',ctx);
test('schema migration preserves old fields, IDs and exact logs; deterministic and repeatable',()=>{const old={schemaVersion:3,habits:[{...h,tracking:'quantity',target:.5,custom:'keep'}],logs:{[h.id+'-2026-09-28']:.5,orphan:false},tasks:[{id:'task',name:'legacy',done:true}],journal:[{id:'j',date:today,text:'note'}],goals:[{id:'g',progress:20}],income:[{id:'inc',amount:10}],expenses:[{id:'expense',amount:2}],lifeAreas:[{id:'area-1',name:'Health',custom:true}],financeCategories:[{id:'cat-1',name:'Other',custom:true}],customRoot:{preserve:true}};const before=JSON.stringify(old),m=ctx.runMigration(old),again=ctx.runMigration(m);assert.equal(JSON.stringify(old),before);assert.deepEqual(m.logs,old.logs);assert.equal(m.habits[0].id,h.id);assert.equal(m.habits[0].target,.5);assert.equal(m.habits[0].journeyStartDate,undefined);assert.equal(m.lifeAreas.find(a=>a.id==='area-1').custom,true);assert.equal(m.financeCategories.find(c=>c.id==='cat-1').custom,true);assert.equal(JSON.stringify(m),JSON.stringify(again));assert.equal(JSON.stringify(ctx.runMigration(old)),JSON.stringify(m));assert.deepEqual(m.customRoot,old.customRoot)});
test('V1 compatibility retains due/status/quantity and log representation',()=>{const old={habits:[{id:'v1',kind:'good',target:5,frequency:'weekly'}],logs:{'v1-2026-09-27':5},tasks:[{id:'t',due:'2026-08-01',status:'Completed',goalId:'g'}]};const m=ctx.runMigration(old);assert.equal(m.habits[0].tracking,'quantity');assert.equal(m.habits[0].frequency,'Weekly');assert.equal(m.tasks[0].date,'2026-08-01');assert.equal(m.tasks[0].done,true);assert.equal(m.tasks[0].goal,'g');assert.deepEqual(m.logs,old.logs)});

test('weekly grids never mark unlogged days as missed',()=>{const weekly={...h,frequency:'Weekly',journeyStartDate:'2026-09-21'},j=D.journey(database({},weekly),weekly,today);assert.equal(j.cells.some(c=>c.state==='missed'),false);assert.equal(j.cycleWeeks[0].state,'missed')});
test('resuming yesterday avoids reset mode',()=>{const habit={...h,journeyStartDate:'2026-09-20'},db=database({[h.id+'-2026-09-28']:true},habit);assert.equal(D.buildDailyState(db,new Date(today+'T10:00:00')).mode,'Execution')});
